/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetails } from './errorDetails';

export interface Error {
  details?: ErrorDetails;
  exceptionType?: string;
  message?: string;
  statusCode?: number;
}
