/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export interface RatingModel {
  ambianceScore?: number;
  foodScore?: number;
  overallScore?: number;
  reviewCount?: number;
  serviceScore?: number;
}
