/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { UserModel } from './userModel';

export interface TokenModel {
  expiration?: string;
  issueTime?: string;
  jwtToken?: string;
  user?: UserModel;
}
