/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { UserAddressModel } from './userAddressModel';
import type { UserModelRole } from './userModelRole';

export interface UserModel {
  address?: UserAddressModel;
  email?: string;
  role?: UserModelRole;
  username?: string;
}
