/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewModel } from './reviewModel';

export interface PagedResponseReviewModel {
  items?: ReviewModel[];
  limit?: number;
  offset?: number;
  totalItems?: number;
}
