/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from './localTime';
import type { RatingModel } from './ratingModel';
import type { RestaurantAddressModel } from './restaurantAddressModel';

export interface RestaurantModel {
  CloseTime?: LocalTime;
  Description?: string;
  ImageUri?: string;
  ManagerUsername?: string;
  Name?: string;
  OpenTime?: LocalTime;
  rating?: RatingModel;
  restaurantAddress?: RestaurantAddressModel;
  Type?: string;
}
