/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewModel {
  ambianceScore?: number;
  comment?: string;
  foodScore?: number;
  issuer?: string;
  issueTime?: string;
  overallScore?: number;
  restaurant?: string;
  serviceScore?: number;
}
