/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AddRestaurantRequest,
  CreateTableRequest,
  EntityCreatedResponse,
  GetAllReviewsParams,
  GetAvailableReserveSlotsParams,
  GetCurrentUserReservesParams,
  GetRestaurantTablesParams,
  LocalTime,
  LocationModel,
  LoginRequest,
  LoginResponse,
  PagedResponseRestaurantModel,
  PagedResponseReviewModel,
  PostReviewParams,
  PostReviewRequest,
  RecommendParams,
  ReserveModel,
  ReserveTableRequest,
  RestaurantModel,
  SearchByTypeParams,
  SignupRequest,
  TableModel
} from './contracts'



  export const getMizdooni = () => {
const signup = <TData = AxiosResponse<LoginResponse>>(
    signupRequest: SignupRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/users`,
      signupRequest,options
    );
  }

const getRestaurantTables = <TData = AxiosResponse<TableModel[]>>(
    params: GetRestaurantTablesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/tables`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const createTable = <TData = AxiosResponse<EntityCreatedResponse>>(
    createTableRequest: CreateTableRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/tables`,
      createTableRequest,options
    );
  }

const login = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/sessions`,
      loginRequest,options
    );
  }

const manageGoogleOauth2Callback = <TData = AxiosResponse<LoginResponse>>(
    manageGoogleOauth2CallbackBody: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/sessions/oauth2`,
      manageGoogleOauth2CallbackBody,options
    );
  }

const getAllReviews = <TData = AxiosResponse<PagedResponseReviewModel>>(
    params: GetAllReviewsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/reviews`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const postReview = <TData = AxiosResponse<void>>(
    postReviewRequest: PostReviewRequest,
    params: PostReviewParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/reviews`,
      postReviewRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getManagerRestaurants = <TData = AxiosResponse<RestaurantModel[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/restaurants`,options
    );
  }

const addRestaurant = <TData = AxiosResponse<void>>(
    addRestaurantRequest: AddRestaurantRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/restaurants`,
      addRestaurantRequest,options
    );
  }

const getCurrentUserReserves = <TData = AxiosResponse<ReserveModel[]>>(
    params?: GetCurrentUserReservesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/reserves`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const reserveTable = <TData = AxiosResponse<EntityCreatedResponse>>(
    reserveTableRequest: ReserveTableRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/reserves`,
      reserveTableRequest,options
    );
  }

const searchByType = <TData = AxiosResponse<PagedResponseRestaurantModel>>(
    params?: SearchByTypeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getRestaurant = <TData = AxiosResponse<RestaurantModel>>(
    name: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/restaurants/${name}`,options
    );
  }

const getAvailableReserveSlots = <TData = AxiosResponse<LocalTime[]>>(
    name: string,
    params: GetAvailableReserveSlotsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/restaurants/${name}/availableTimeSlots`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getReserveDetails = <TData = AxiosResponse<ReserveModel>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/reserves/${id}`,options
    );
  }

const cancelReserve = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/reserves/${id}`,options
    );
  }

const recommend = <TData = AxiosResponse<RestaurantModel[]>>(
    params?: RecommendParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/recommend`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getLocations = <TData = AxiosResponse<LocationModel[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/locations`,options
    );
  }

const getFoodTypes = <TData = AxiosResponse<string[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/foodTypes`,options
    );
  }

return {signup,getRestaurantTables,createTable,login,manageGoogleOauth2Callback,getAllReviews,postReview,getManagerRestaurants,addRestaurant,getCurrentUserReserves,reserveTable,searchByType,getRestaurant,getAvailableReserveSlots,getReserveDetails,cancelReserve,recommend,getLocations,getFoodTypes}};
export type SignupResult = AxiosResponse<LoginResponse>
export type GetRestaurantTablesResult = AxiosResponse<TableModel[]>
export type CreateTableResult = AxiosResponse<EntityCreatedResponse>
export type LoginResult = AxiosResponse<LoginResponse>
export type ManageGoogleOauth2CallbackResult = AxiosResponse<LoginResponse>
export type GetAllReviewsResult = AxiosResponse<PagedResponseReviewModel>
export type PostReviewResult = AxiosResponse<void>
export type GetManagerRestaurantsResult = AxiosResponse<RestaurantModel[]>
export type AddRestaurantResult = AxiosResponse<void>
export type GetCurrentUserReservesResult = AxiosResponse<ReserveModel[]>
export type ReserveTableResult = AxiosResponse<EntityCreatedResponse>
export type SearchByTypeResult = AxiosResponse<PagedResponseRestaurantModel>
export type GetRestaurantResult = AxiosResponse<RestaurantModel>
export type GetAvailableReserveSlotsResult = AxiosResponse<LocalTime[]>
export type GetReserveDetailsResult = AxiosResponse<ReserveModel>
export type CancelReserveResult = AxiosResponse<void>
export type RecommendResult = AxiosResponse<RestaurantModel[]>
export type GetLocationsResult = AxiosResponse<LocationModel[]>
export type GetFoodTypesResult = AxiosResponse<string[]>
