apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mishap
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    app: frontend
