apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mishap
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.4.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "mizdooni_db"
        - name: MYSQL_USER
          value: "mizdooni_db_user"
        - name: MYSQL_PASSWORD
          value: "Mizd00N!!"
        - name: MYSQL_ROOT_PASSWORD
          value: "Mizd00N!!@@db@@root@@password"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc