/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export * from './addRestaurantRequest';
export * from './createTableRequest';
export * from './entityCreatedResponse';
export * from './error';
export * from './errorDetails';
export * from './getAllReviewsParams';
export * from './getAvailableReserveSlotsParams';
export * from './getCurrentUserReservesParams';
export * from './getRestaurantTablesParams';
export * from './googleOauth2CallbackParams';
export * from './localTime';
export * from './locationModel';
export * from './loginRequest';
export * from './loginResponse';
export * from './pagedResponseRestaurantModel';
export * from './pagedResponseReviewModel';
export * from './postReviewParams';
export * from './postReviewRequest';
export * from './ratingModel';
export * from './recommendParams';
export * from './reserveModel';
export * from './reserveTableRequest';
export * from './restaurantAddressModel';
export * from './restaurantModel';
export * from './reviewModel';
export * from './searchByTypeParams';
export * from './signupRequest';
export * from './tableModel';
export * from './tokenModel';
export * from './userAddressModel';
export * from './userModel';
export * from './userModelRole';