/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { RestaurantModel } from './restaurantModel';

export interface PagedResponseRestaurantModel {
  items?: RestaurantModel[];
  limit?: number;
  offset?: number;
  totalItems?: number;
}
