/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export interface PostReviewRequest {
  ambientRate?: number;
  comment?: string;
  foodRate?: number;
  overallRate?: number;
  serviceRate?: number;
}
