/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */
import type { RestaurantAddressModel } from './restaurantAddressModel';

export interface ReserveModel {
  address?: RestaurantAddressModel;
  isCanceled?: boolean;
  reservee?: string;
  reserveTime?: string;
  restaurant?: string;
  tableNumber?: number;
}
