/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export interface SignupRequest {
  /**
   * @minLength 2
   * @maxLength 128
   */
  city?: string;
  /**
   * @minLength 2
   * @maxLength 128
   */
  country?: string;
  email?: string;
  password: string;
  /** @pattern (client|manager) */
  role?: string;
  username: string;
}
