/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Mizdooni
 * OpenAPI spec version: 1.0.0
 */

export type UserModelRole = typeof UserModelRole[keyof typeof UserModelRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserModelRole = {
  Manager: 'Manager',
  Client: 'Client',
} as const;
